### ISSUE TITLE
Linear to Logarithmic conversion

### ISSUE THREAD

**Issue by Dean-Coakley** [AnttiVainio/FMOD-music-visualizer#1]
Hi,

Great looking project!

Can you tell me where in your code do you convert from linear to logarithmic scale? Or can you describe how to do this? 

Thanks.

**Comment by AnttiVainio** [comment]
Hello

This is done in visualizer.cpp in visualizer_c::run function. There are actually two different types of bars that can be selected from the code. The default is 1 that is a fixed width bar whose code starts on line 61. Bar 2 is the variable width bar and its code starts on line 104.

If you are trying to understand how this works I suggest you to look at the bar 2 code first because there are some actual calls to the log function.
